### ISSUE TITLE
Unable to send test email

### ISSUE THREAD

**Issue by senguttuvang** [sinclairnick/brail#29]
It is unclear from the documentation on how to send test email. Is this email handled in server side React or do we need Node us? Shall we use Laravel for dynamic/merge data and sending and use Brail for composing the email templates? Can we have any examples in the documentation? If we need to add SMPT, which part of the code do we need to do it?

**Comment by sinclairnick** [comment]
You can set the `onSend` method for a template which allows sending emails, in general. To specifically send a test email, we can use the Brail Devtools, which will call this `onSend` method we've attached to a template.

You can play around with this in a [playground](https://stackblitz.com/edit/sinclairnick-brail-mdetoj?file=src%2Fbrail%2Fbase.ts&initialPath=/account/sign-up) by clicking the email icon in the toolbar of the Devtools UI, and sending the email via the an API of your choice.
