### ISSUE TITLE
Call for contributions? 

### ISSUE THREAD

**Issue by Scott-Fischer** [sinclairnick/brail#6]
Just wanted to say that I'm very excited by this project! MJML was a really great innovation but it has terrible DX when it comes to actually implementing it, and the authors have made it pretty clear that they do not intend to fix that. 

There's a banner at the bottom of the docs page that brail is looking for contributions. Is there a more detailed list of todos? I would love to get involved in my spare time if possible.

**Comment by sinclairnick** [comment]
Glad to hear! I've had a similar experience with MJML. With this project I'm hoping we can, once and for all, modernise it all and tie it in a nice bow so email's not such a headache.

As for contributions: I most certainly have a long laundry list of improvements and fixes I've accrued via putting together this beta rewrite. Currently, they're just living in my Notes app, but I'll pore over them, get them organised and upload them to this repo. I can give you a ping once I've done that.

Thanks for the interest, I'll keep you posted!

**Comment by sinclairnick** [comment]
Hey @Scott-Fischer, I've added ~20 tickets which are just the first things that come to mind. Many of them are documentation tickets, so feel free to ignore those. And also feel free to open any new issues or discussions if you have any feature requests etc. too. Interested to hear what you'd like to see added!
