### ISSUE TITLE
[Docs]: incorrect url in beta release banner

### ISSUE THREAD

**Issue by Scott-Fischer** [sinclairnick/brail#7]
Just wanted to point out that this link points to `http://localhost:3001/docs/introduction` which is probably unintentional. 

<img width="323" alt="image" src="https://user-images.githubusercontent.com/8835133/224828346-2d5a3993-dff7-4d9e-b445-0659efb80aec.png">

**Comment by sinclairnick** [comment]
Thanks I've now fixed this 👍
